test(user): User 저장 및 id로 조회
seeyouletter/seeyouletter-be pull request #11
Opened 2022-12-24 09:06 UTC by Msukoo

## 💌 설명

회원 생성 시 필요한 기본적인 필드들만 추가하여 entity 생성했습니다.
소셜로그인 후 필요한 필드들이 정확하게 정해지면 바뀔 수 있음.
1. Entity 이름 변경
- `Users` -> `User`
- 동일하게 `User`를 테이블명으로 사용할 경우 SQL의 키워드이기 때문에 사용할 수 없음
- 테이블명은 `Users`로 명시
3. 기본적인 테스트 코드 작성
- User 저장, id로 조회하는 repository 테스트코드 작성

## 📎 관련 이슈

해당 이슈가 완벽하게 구현되지 않았고 일단 기본 entity만 생성하였기 때문에 나중에 입력해야겠습니다.

## 💡 논의해볼 사항

소셜로그인 시 받을 정보를 논의해야합니다.
각 벤더사별로 어떤정보를 필수, 선택으로 받을 수 있을지 저도 좀더 찾아보겠습니다~~

## 📝 참고자료

## ⚠️ 잠깐! 한 번 체크해주세요.

- [ ] 베이스가 제대로 적용되었나요?
- [ ] 코드의 변경사항은 원하는 대로 잘 되었는지 다시 한 번 살펴봐요!

2022-12-25 04:35 UTC, sinbom requested changes
현재 시점에서 Users 엔티티를 명확하게 설계하는 것은 어렵겠지만 충분히 고려해볼 수 있는 점들에 대해서만 리뷰를 남겼습니다. 😊

2022-12-25 04:35 UTC, sinbom commented on domain-member/src/main/java/com/seeyouletter/domain_member/entity/User.java
> +    private Date birth;
`java.util.Date`와 `java.util.Calendar`는 각 JDK 1 version에 포함된 API 입니다. 하지만 많은 문제들로 인해 현재는 JDK 8부터 지원하는 `java.time.LocalDate`를 사용하는 것이 권장되고 있습니다. 자세하게 잘 정리된 내용을 참고해보세요.

[Naver D2 - Java의 날짜와 시간 API](https://d2.naver.com/helloworld/645609)

2022-12-25 04:35 UTC, sinbom commented on domain-member/src/main/java/com/seeyouletter/domain_member/entity/User.java
> +    private String gender;
성별과 같은 컬럼은 [데이터 도메인](https://en.wikipedia.org/wiki/Data_domain)이 정해져있습니다. 데이터베이스 레벨에서 [도메인 제약조건을 지정](https://www.postgresql.org/docs/current/sql-createdomain.html)하여 허용된 값만을 입력할 수 있도록 강제할 수 있는 방법이 있으며, ORM을 사용하는 애플리케이션 레벨에서 `Enum` 클래스와 `@Enumerated` 애노테이션을 사용해서 강제할 수 있습니다. 데이터베이스에서 직접 데이터를 수정하지 않고 애플리케이션을 통해서만 데이터의 CUD가 일어나야 하며, 후자의 방법을 사용하는 것이 ORM에서는 적합해보입니다.

2022-12-25 04:35 UTC, sinbom commented on domain-member/src/main/java/com/seeyouletter/domain_member/entity/User.java
> +    }
생성자의 인자가 email, phone, gender, birth로 구성되어 있는 이유에 대해서 궁금합니다 🤔
인자가 많고, 필수가 아닌 nullable한 인자가 많은 경우에는 생성자의 갯수가 많아지거나 인자가 많은 생성자를 사용하게 됩니다. 빌더 패턴을 적용해도 좋을지 고민해주시면 좋을 것 같습니다 🙏

2022-12-25 04:35 UTC, sinbom commented on domain-member/src/main/java/com/seeyouletter/domain_member/repository/UserRepository.java
> +
다음부터는 반드시 파일명 변경으로 해주세요 🙏 파일의 히스토리가 사라지기 때문입니다 😂

2022-12-31 07:10 UTC, Msukoo commented on domain-member/src/main/java/com/seeyouletter/domain_member/entity/User.java
> +    private Date birth;
`java.time.LocalDate` 을 사용할때 좀더 직관적으로 쓸 수 있군요.

2022-12-31 07:13 UTC, Msukoo commented on domain-member/src/main/java/com/seeyouletter/domain_member/repository/UserRepository.java
> +
🙆🏻‍♀️ 인텔리제이 사용법이 미숙하여 renaming에 착오가 있었습니다 허허

2022-12-31 07:14 UTC, Msukoo commented on domain-member/src/main/java/com/seeyouletter/domain_member/entity/User.java
> +    private String gender;
이 부분은 뜻을 받아드려 수정하였습니다. 사실 `Enum` 으로 관리할때 `AttributeConverter`를 사용하여 관리할 수 있다는것을 이번 기회에 알게 되었습니당.

2022-12-31 07:22 UTC, Msukoo commented on domain-member/src/main/java/com/seeyouletter/domain_member/entity/User.java
> +    }
생성자의 인자는 큰 뜻 없이 필수값으로 생각되는 필드값들로 정의해둔 것 이기 때문에 추후에 얼마든지 변경이 가능합니다. 
저는 생성자로 만들었을 시 (생성자 or static factory) 직관성과 강력크한 vaildation을 염두해 두고 생성자를 선호하려고 했으나
@sinbom 님의 빌더패턴을 사용할시에 장점(확장성, vaildation완료된 후에 객체생성) 들을 듣고 이번에는 빌더패턴으로 채택했습니다.
왜냐하면 어떤 밴더사의 객체를 생성하느냐에 따라 필드값의 유무가 다르기 때문에 이미 vaildation이 된상태라면 필요한 값으로만 바인딩하여 생성하는것이 좋을 것 같았기 때문이에요
그리고 제일 큰 이유는 seeyouletter는 큰 서비스가 될것 이기 때문입니다.

2022-12-31 07:24 UTC, sinbom commented on domain-member/src/main/java/com/seeyouletter/domain_member/entity/User.java
> +    }
먼소린진 잘 모르겠지만... 👍

2022-12-31 07:37 UTC, sinbom requested changes
리뷰 내용에 대해서 긍정적으로 검토해주시고 수정해주셔서 감사합니다. 추가적으로 필요해보이는 수정사항이 있는데 확인 부탁드립니다!

2022-12-31 07:37 UTC, sinbom commented on domain-member/src/main/java/com/seeyouletter/domain_member/enums/converter/GenderTypeConverter.java
> +        if (Objects.isNull(genderType)) {
객체 null 상태를 확인할 떄, object == null을 사용할지 Objects.isNull을 사용할지 결정하여 일관성 있게 사용하면 좋을 것 같습니다. Object.isNull은 Method Reference에서 사용하는 케이스가 아니면 굳이 사용하는 부분에서 장점이 있어보이지는 않습니다.

```java
List<Integer> list = Arrays.asList(1, null);

List<Integer> filteredNullList = list
               .stream()
               .filter(Objects::isNull)
               .collect(Collectors.toList());
```

2022-12-31 07:37 UTC, sinbom commented on domain-member/src/main/java/com/seeyouletter/domain_member/enums/converter/GenderTypeConverter.java
> +        if (gender == null) {
여기서는 null 비교에서 단순 equals 연산자를 사용했는데, 일관성이 필요할 것 같습니다.

2022-12-31 07:37 UTC, sinbom commented on domain-member/src/test/resources/application.yml
> +              MongoTemplate: DEBUG
`domain-member` 모듈에서는 data-mongo 의존성은 포함되어 있지 않습니다. 관련 로깅 레벨 설정은 제거해주세요 🙏

2022-12-31 07:37 UTC, sinbom commented on domain-member/src/main/java/com/seeyouletter/domain_member/entity/User.java
> +    }
전체 필드를 대상으로 빌더를 적용할 것이고 추가적인 로직이 들어가지 않는다면 클래스 레벨에 `@Builder` 애노테이션을 적용해도 좋을 것 같습니다.

2022-12-31 07:50 UTC, sinbom approved these changes

2022-12-31 07:50 UTC, merged