feat(api-member): seeyouletter 로그인 구현(AuthenticationProvider token생성)
seeyouletter/seeyouletter-be pull request #33
Opened 2023-01-27 17:24 UTC by bulmandu

## 💌 설명

## 📎 관련 이슈

closes #14

## 💡 논의해볼 사항

## 📝 참고자료

## ⚠️ 잠깐! 한 번 체크해주세요.

- [ ] 베이스가 제대로 적용되었나요?
- [ ] 코드의 변경사항은 원하는 대로 잘 되었는지 다시 한 번 살펴봐요!

2023-02-15 07:57 UTC, sinbom requested changes
작성하신 내용 잘 봤습니다. 고생 많으셨어요 👍
리뷰 작성했으니 확인해보시고 피드백 주시면 감사하겠습니다 😀

2023-02-15 07:57 UTC, sinbom commented on api-member/src/main/java/com/seeyouletter/api_member/auth/config/PrincipalDetails.java
> +    }
현재 커스텀한 `AuthenticationProvider` 구현체인 `AuthenticationProviderImpl`을 사용하고 있고, 해당 구현체에서 이 필드들을 검증하고 않기 때문에 정상적으로 로그인이 되고 있긴 합니다. 하지만 이 필드들이 각각 계정이 잠기지 만료가 되지 않았는지, 잠기지 않았는지, 비밀번호가 만료되지 않았는지를 의미하기 때문에 리턴하는 값이 반대가 되어야할 것 같습니다.

2023-02-15 07:57 UTC, sinbom commented on api-member/src/main/java/com/seeyouletter/api_member/auth/service/CustomOAuth2UserService.java
>      }
지난번에 말씀드렸지만 Oauth 유저의 가입 과정을 하나의 트랜잭션 단위로 처리할 수 있도록 추후에 변경이 필요할 것 같습니다. 나중에 좋은 방법이 떠오르시면 변경해주세요.

2023-02-15 07:57 UTC, sinbom commented on api-member/src/main/java/com/seeyouletter/api_member/config/AuthenticationProviderImpl.java
> +}
스프링 시큐리티에서 제공하는 `AuthenticationProvider` 기본 구현체를 사용하지 않고 커스텀한 구현체를 사용하는 이유가 궁금합니다.

2023-02-15 07:57 UTC, sinbom commented on api-member/src/main/java/com/seeyouletter/api_member/auth/service/UserDetailsServiceImpl.java
> +}
`UserDetailsService` 구현체인 `UserDetailsServiceImpl`를 정의하여 사용할 예정이니 이전에 개발되기 전에 임시로 사용하던 인메모리 구현체는 제거해주세요.

```
// 제거가 필요한 구현체
@Bean
public UserDetailsService userDetailsService() {
    UserDetails user = User
            .withDefaultPasswordEncoder()
            .username("user")
            .password("password")
            .roles("USER")
            .build();

    return new InMemoryUserDetailsManager(user);
}
```

2023-02-15 07:57 UTC, sinbom commented on api-member/src/main/java/com/seeyouletter/api_member/config/SecurityConfiguration.java
> +                .and()
스프링 시큐리티에서 지원하는 로그인 API를 클라이언트에 제공하고자하는 의도로 이해했습니다. 현재 상태에서 클라이언트가 사용하기 적합한 방식일지 @JengYoung님과 협의해볼 필요가 있는 것으로 보입니다. 예를들어 현재는 로그인 성공 또는 실패시에 모두 302 리다이렉트가 응답이 될 것인데, 클라이언트가 별도의 서버 요청 없이 로그인 성공/실패 여부를 판단하려면 응답 `Location` 헤더의 리다이렉트 url 값으로 밖에 판단이 불가능해보입니다. 또한 응답시에 필요한 응답 데이터가 있을지 협의 후에 별도로 로그인 API를 구현해야할 수도 있을 것 같습니다.

2023-02-16 07:59 UTC, bulmandu commented on api-member/src/main/java/com/seeyouletter/api_member/auth/config/PrincipalDetails.java
> +    private Map<String, Object> attributes;
막연하게 불변이라고는 생각하지 않았는데 생각해보니 한번 PrincipalDetails가 만들어지면 필드들이 바뀌지 않네요!

2023-02-16 07:59 UTC, bulmandu commented on api-member/src/main/java/com/seeyouletter/api_member/auth/config/PrincipalDetails.java
> +    }
헉쓰 의미를 다르게 이해했어요 만료되지않았다, false 리턴이 "잠기지않았다"로 이해했네요😅

2023-02-16 07:59 UTC, bulmandu commented on api-member/src/main/java/com/seeyouletter/api_member/auth/service/CustomOAuth2UserService.java
>      }
넹 추후에 새로운 pr로 적용해보겠어요

2023-02-16 07:59 UTC, bulmandu commented on api-member/src/main/java/com/seeyouletter/api_member/config/SecurityConfiguration.java
> +                .and()
아 네 맞습니다 성공이나 실패시 어떤 처리를 할지 정해지지 않아 임시로 "/"라고 정해두었습니다. pr 논의할 부분에 들어갔어야 할 내용인데 빠졌네요!

2023-02-16 07:59 UTC, bulmandu commented on api-member/src/main/java/com/seeyouletter/api_member/config/AuthenticationProviderImpl.java
> +}
AuthenticationProvider 는 인터페이스로 되어있어 커스텀한 구현이 필요하다고 생각되어 당연하게(?) 재구현하게 되었습니다. 
그리고 추후에 다른 인증절차가 추가될 경우(만료등) 상황에 맞춰 구현할 일이 있지않을까요?😮

2023-02-16 07:59 UTC, bulmandu commented on api-member/src/main/java/com/seeyouletter/api_member/auth/service/UserDetailsServiceImpl.java
> +}
이건 지워야겠네요🥲

2023-02-16 09:28 UTC, sinbom commented on api-member/src/main/java/com/seeyouletter/api_member/config/AuthenticationProviderImpl.java
> +}
스프링 시큐리티는 `UserDetailsService` 타입의 빈이 존재한다면 `AuthenticationProvider` 구현체인 `DaoAuthenticationProvider`를 인증에 사용하도록 `AuthenticationManager`에 설정합니다.

- [DaoAuthenticationProvider를 사용하도록 설정 하는 부분](https://github.com/spring-projects/spring-security/blob/28d353d73134e368e53eb1b25ca6c03a7ab18703/config/src/main/java/org/springframework/security/config/annotation/authentication/configuration/InitializeUserDetailsBeanManagerConfigurer.java#L57-L78)
- [DaoAuthenticationProvider에 의해 인증이 수행되는 흐름](https://docs.spring.io/spring-security/reference/servlet/authentication/passwords/dao-authentication-provider.html)

2023-02-17 03:09 UTC, JengYoung commented on api-member/src/main/java/com/seeyouletter/api_member/config/SecurityConfiguration.java
> +                .and()
에구 멘션을 이제야 보았네요 😖
로그인 API를 `/login`에서 로그인을 시도할 때 사용할 API로 해석하고 답변드립니다!

클라이언트가 로그인에서 성공 시 아마 받을 것은 API 사용 권한을 얻을 수 있는 토큰 정도가 되지 않을까 싶읍니다!

또한, 리다이렉트의 경우 클라이언트 측에서 자체적으로 처리해줄 수 있을 것 같아요 🙆🏻
추후 `status`의 의미만 잘 전달해주시면 에러 메시지 처리도 수월하게 될 듯 하옵니다!

2023-02-18 06:18 UTC, bulmandu commented on api-member/src/main/java/com/seeyouletter/api_member/config/AuthenticationProviderImpl.java
> +}
그냥 재구현해서 써야하는 인터페이스인줄 알았는데 DaoAuthenticationProvider가 있는 줄 몰랐네요 재구현 해봤다는데 의미가 있으니 제 구현체는 삭제했습니다

2023-02-18 06:42 UTC, bulmandu commented on api-member/src/main/java/com/seeyouletter/api_member/auth/service/UserDetailsServiceImpl.java
> +}
@sinbom 지웠습니당!

2023-02-18 06:42 UTC, bulmandu commented on api-member/src/main/java/com/seeyouletter/api_member/config/SecurityConfiguration.java
> +                .and()
@JengYoung 아직 로그인 후 세션처리 작업이 되지않아 그부분 완료하면서 다시 논의드릴게요!

2023-02-18 06:42 UTC, bulmandu commented on api-member/src/main/resources/data.sql
> +VALUES('email@gmail.com', '$2a$10$IAMyFV/oYs3EwmIFjYG8LuryFS2oSIKOlYw19.LRiYmwZ218uwZs6', '김레터', 'M', '1992-08-02', '01094949494', '2023-01-28 02:16:23');
@sinbom 회원가입 로직을 구현하기전까지 default로 사용할 유저 정보를 넣었습니다 해당 정보로 로그인 부탁드려욧

2023-02-18 06:42 UTC, bulmandu commented on api-member/src/test/resources/application-test.yml
> +      mode: never
왜인지는 모르겠지만 test.yml에 data.sql Insert를 명시적으로 비활성화해주니 그제서야 작동하지않았습니다🥲

2023-02-18 06:59 UTC, bulmandu commented on api-member/src/test/resources/application-test.yml
> +      mode: never
@sinbom 기본값이 embeded 이기때문에 h2데이터베이스를 쓰는 test환경에서 돌아갔군요!

2023-02-18 07:20 UTC, sinbom requested changes
피드백 반영해주셔서 감사합니다. 추가 코멘트 확인 부탁드립니다 ❤️

2023-02-18 07:20 UTC, sinbom commented on api-member/src/test/resources/application-test.yml
> +      mode: never
각 `spring.sql.init.mode` 값이 가지는 의미는 아래와 같습니다.
> `ALWAYS`: 항상 초기화 스크립트를 수행합니다.
> `EMBEDDED`: 오직 `H2`와 같은 내장 데이터베이스를 사용하는 경우에만 수행합니다(ex: 테스트 환경)
> `NEVER` 항상 초기화 스크립트를 수행하지 않습니다.

따라서 테스트 환경에서는 현재 `H2`를 사용하고 있기 때문에 `never`로 지정해주지 않으면 초기화 스크립트가 실행되고, 로컬 환경에서는 마찬가지로 `H2`를 사용하고 있지 않기 때문에 `always`로 지정해주어야 실행됩니다.

[DatabaseInitializationMode 각 init mode에 대한 Enum 정의](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/sql/init/DatabaseInitializationMode.java)

2023-02-18 07:20 UTC, sinbom commented on api-member/src/main/resources/application-local.yml
> +      mode: always
어떤 초기화 스크립트가 수행되었는지, 잘 수행되었는지 확인할 수 있도록 로깅 설정을 추가해주세요.

```yaml
logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init:
              ScriptUtils: DEBUG
```

자세한 내용은 초기화 스크립트를 수행하는 `ScriptUtils` 클래스의 [소스 코드](https://github.com/spring-projects/spring-framework/blob/main/spring-jdbc/src/main/java/org/springframework/jdbc/datasource/init/ScriptUtils.java)를 참고해주세요 😉

2023-02-18 07:20 UTC, sinbom commented on api-member/src/main/resources/data.sql
> +VALUES('email@gmail.com', '$2a$10$IAMyFV/oYs3EwmIFjYG8LuryFS2oSIKOlYw19.LRiYmwZ218uwZs6', '김레터', 'M', '1992-08-02', '01094949494', '2023-01-28 02:16:23');
번거로우시겠지만 `admin@seeyouletter.kr` 계정으로 생성할 수 있도록 수정 부탁드리겠습니다 🙏 사전에 @JengYoung 님과 해당 계정으로 사용하기로 협의를 했었는데 @bulmandu 님께 공유를 안드렸네요 😂

비밀번호는 해당 PR에 남기지 말고 [노션 페이지](https://www.notion.so/148ffb19ae614f05a7502db147331759?pvs=4)에 공유 부탁드립니다 🙇‍♂️

2023-02-18 07:48 UTC, bulmandu commented on api-member/src/main/resources/application-local.yml
> +      mode: always
로깅 적용하였고 로그인 정보 수정하고 노션에 공유드렸습니다.

2023-02-18 07:51 UTC, bulmandu commented on api-member/src/main/java/com/seeyouletter/api_member/auth/config/PrincipalDetails.java
> +    private final Map<String, Object> attributes;
@sinbom 말씀을 들어보니 생성자가 다르더라도 정보가 없을 시 더더욱 null로 불변하게 만들어주는게 나을것 같아서 적용했습니당

2023-02-18 07:58 UTC, sinbom approved these changes

2023-02-18 07:58 UTC, merged