test(api-member): Rest API 로그인 테스트 코드를 추가한다.
seeyouletter/seeyouletter-be pull request #59
Opened 2023-03-12 10:08 UTC by bulmandu

## 💌 설명

Rest API 로그인 e2e 테스트 코드를 아래의 3가지 케이스로 추가했습니다.
- 성공
- 등록되어 있지 않은 아이디
- 잘못된 패스워드

## 📎 관련 이슈

#53 

## 💡 논의해볼 사항

## 📝 참고자료

## ⚠️ 잠깐! 한 번 체크해주세요.

- [ ] 베이스가 제대로 적용되었나요?
- [ ] 코드의 변경사항은 원하는 대로 잘 되었는지 다시 한 번 살펴봐요!

2023-03-15 09:43 UTC, sinbom requested changes
테스트 코드 작성 경험이 없었는데, 잘 작성하신 것 같습니다! 테스트 해볼 수 있는 더 다양한 케이스가 있는지 고민해보시고, Restdocs 문서화를 위한 코드 작성도 함께 진행해보세요!

2023-03-15 09:43 UTC, sinbom commented on api-member/src/test/java/com/seeyouletter/api_member/e2e/RestAuthenticationTest.java
> +@Nested
해당 애노테이션은 중첩 구조의 테스트 메소드를 위한 애노테이션입니다.

2023-03-15 09:43 UTC, sinbom commented on api-member/src/test/java/com/seeyouletter/api_member/e2e/RestAuthenticationTest.java
> +    }
테스트를 위한 `User` 엔티티를 `@BeforeAll` 메소드에서 영속화를 하고 있네요! 모든 테스트 클래스의 모든 테스트를 수행하고 다른 테스트 클래스의 테스트를 수행할 때, 동일한 테스트 애플리케이션 컨텍스트에 속한 테스트들의 결과에 영향을 미치지 않으려면 테스트를 위해 영속화한 데이터를 지워주어야합니다. `@AfterAll` 메소드를 통해 해당 작업을 진행해주세요

2023-03-18 04:59 UTC, bulmandu commented on api-member/src/test/java/com/seeyouletter/api_member/e2e/RestAuthenticationTest.java
> +    }
테스트 코드 경험이 없어서 이런부분 까지 생각을 못했네요 이건 JPA를 잘 사용하지 못한다는 의미이기도 하네요 허허허😅
다른 테스트 코드에 영향이 가지않으려면 이 컨텍스트의 모든 테스트들이 끝나고 사용했던 데이터를 모두 삭제해줘야 하는걸 깨달았습니다.

2023-03-18 04:59 UTC, bulmandu commented on api-member/src/test/java/com/seeyouletter/api_member/e2e/RestAuthenticationTest.java
> +@Nested
이 케이스에선 중첩을 의미하는 @nested가 굳이 필요가 없군요!

2023-03-18 05:19 UTC, sinbom approved these changes

2023-03-18 05:19 UTC, merged